env:
  sandbox_url: "https://api.sandbox.competitions.recall.network"
  production_url: "https://api.competitions.recall.network"

chains:
  - name: "eth"
    chain: "evm"
    specific: "eth"
    starting_usdc: 5000
  - name: "polygon"
    chain: "evm"
    specific: "polygon"
    starting_usdc: 5000
  - name: "bsc"
    chain: "evm"
    specific: "bsc"
    starting_usdc: 5000
  - name: "arbitrum"
    chain: "evm"
    specific: "arbitrum"
    starting_usdc: 5000
  - name: "base"
    chain: "evm"
    specific: "base"
    starting_usdc: 5000
  - name: "optimism"
    chain: "evm"
    specific: "optimism"
    starting_usdc: 5000
  - name: "avalanche"
    chain: "evm"
    specific: "avalanche"
    starting_usdc: 5000
  - name: "solana"
    chain: "solana"
    specific: "mainnet"
    starting_usdc: 5000

token_filters:
  min_age_hours: 4380
  min_24h_volume_usd: 500000
  min_liquidity_usd: 500000
  min_fdv_usd: 1000000

strategy:
  bar_seconds: 45
  lookback_short: 20
  lookback_long: 100
  vol_lookback: 80
  z_entry: 1.2
  z_exit: 0.3
  min_momentum: 0.005
  momentum_threshold: 0.01

risk:
  min_daily_trades: 3
  max_daily_trades: 120
  cooldown_seconds: 20
  max_single_trade_pct: 0.25
  per_trade_base_usd: 100
  max_drawdown_stop: 0.18
  slippage_tolerance_pct: 1.0
  max_exposure_per_asset_pct: 0.35
  
portfolio:
  rebalance_every_sec: 180
  target_cash_frac: 0.15
  risk_parity: true
  max_assets: 8
  
telemetry:
  csv_path: "telemetry_equity.csv"
  log_every_sec: 300

rate_limits:
  trade_operations: 100
  price_queries: 300
  balance_checks: 30
  global_rpm: 3000
  global_rph: 10000
